"""soft delete: coluna deleted_at

Revision ID: f4db31f01f37
Revises: d7943ce1ca5e
Create Date: 2026-09-29 13:39:25.715987

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4db31f01f37"
down_revision: str | Sequence[str] | None = "d7943ce1ca5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("subjects", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("topics", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topics", "deleted_at")
    op.drop_column("subjects", "deleted_at")
    op.drop_column("notes", "deleted_at")
    # ### end Alembic commands ###
